<?php

use Illuminate\Database\Seeder;

use App\ObjectType;
use App\Organisation;
use App\Application;
use App\ApplicationPet;
use App\Client;
use App\Pet;
use App\Phone;
use App\Address;
use App\User;

class ClientApplicationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // get organisation type id for advocate
        $advocateTypeOrg = ObjectType::where([
                            ['type', '=', 'organisation'],
                            ['value', '=', 'advocate']
                        ])->first();
        
        // get list of advocate organisations
        $organisations = Organisation::where('org_type_id', $advocateTypeOrg->id)->get();

        // demo data for applications, clients and pets
        $demoEntries = [
            [
                'client-first-name' => 'Noelyn',
                'client-last-name' => 'Impett',
                'client-email' => 'nimpett0@tripadvisor.com',
                'pet-type' => 'dog',
                'pet-name' => 'Duke',
                'pet-breed' => 'no',
                'pet-weight' => 40,
                'pet-age' => 8,
                'pet-description' => 'no',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => 'no',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => 'no',
                'pet-relevant-info' => 'no',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5717851256',
                'client-state' => 'Virginia',
                'client-city' => 'vienna',
                'client-address' => '12758 Farragut Terrace',
                'client-zip' => '185369',
            ],
            [
                'client-first-name' => 'Thebault',
                'client-last-name' => 'Wattingham',
                'client-email' => 'twattingham1@flavors.me',
                'pet-type' => 'cat',
                'pet-name' => 'Mike',
                'pet-breed' => 'Persian cat',
                'pet-weight' => 6,
                'pet-age' => 9,
                'pet-description' => 'no',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => 'no',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => 'no',
                'pet-relevant-info' => 'no',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => 'no',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '9516948666',
                'client-state' => 'California',
                'client-city' => 'Moreno Valley',
                'client-address' => '02 Bonner Place',
                'client-zip' => '111555',
            ],
            [
                'client-first-name' => 'Claresta',
                'client-last-name' => 'Brahams',
                'client-email' => 'cbrahams2@usda.gov',
                'pet-type' => 'dog',
                'pet-name' => 'Doggy',
                'pet-breed' => 'mix',
                'pet-weight' => 15,
                'pet-age' => 2,
                'pet-description' => 'no',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => 'no',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '8477218270',
                'client-state' => 'Illinois',
                'client-city' => 'Palatine',
                'client-address' => '21 Norway Maple Parkway',
                'client-zip' => '123456',
            ],
            [
                'client-first-name' => 'Andrea',
                'client-last-name' => 'Andrasch',
                'client-email' => 'candrasch3@wix.com',
                'pet-type' => 'dog',
                'pet-name' => 'Blah',
                'pet-breed' => '-',
                'pet-weight' => 8,
                'pet-age' => 10,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '8323206108',
                'client-state' => 'Texas',
                'client-city' => 'Houston',
                'client-address' => '98 Buena Vista Trail',
                'client-zip' => '3698521',
            ],
            [
                'client-first-name' => 'Wilie',
                'client-last-name' => 'Titterton',
                'client-email' => 'wtitterton4@a8.net',
                'pet-type' => 'dog',
                'pet-name' => 'Will',
                'pet-breed' => '-',
                'pet-weight' => 12.3,
                'pet-age' => 11,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '2695178991',
                'client-state' => 'Michigan',
                'client-city' => 'Kalamazoo',
                'client-address' => '892 Morning Lane',
                'client-zip' => '741258',
            ],
            [
                'client-first-name' => 'Inez',
                'client-last-name' => 'Hamlen',
                'client-email' => 'ihamlen5@dagondesign.com',
                'pet-type' => 'dog',
                'pet-name' => 'Ini',
                'pet-breed' => '-',
                'pet-weight' => 3,
                'pet-age' => 1,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '4401926432',
                'client-state' => 'Ohio',
                'client-city' => 'Cleveland',
                'client-address' => '25730 Bay Place',
                'client-zip' => '789654',
            ],
            [
                'client-first-name' => 'Eberhard',
                'client-last-name' => 'Tander',
                'client-email' => 'etander6@thetimes.co.uk',
                'pet-type' => 'cat',
                'pet-name' => 'Cat',
                'pet-breed' => '-',
                'pet-weight' => 5.5,
                'pet-age' => 12,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5042117188',
                'client-state' => 'Louisiana',
                'client-city' => 'New Orleans',
                'client-address' => '1823 Quincy Way',
                'client-zip' => '789656',
            ],
            [
                'client-first-name' => 'Pamella',
                'client-last-name' => 'Lyst',
                'client-email' => 'plyst7@tinypic.com',
                'pet-type' => 'cat',
                'pet-name' => 'Pam',
                'pet-breed' => '-',
                'pet-weight' => 4,
                'pet-age' => 3,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '6015673283',
                'client-state' => 'Mississippi',
                'client-city' => 'Jackson',
                'client-address' => '4 Riverside Plaza',
                'client-zip' => '258963',
            ],
            [
                'client-first-name' => 'Conrad',
                'client-last-name' => 'Rodolico',
                'client-email' => 'crodolico8@statcounter.com',
                'pet-type' => 'dog',
                'pet-name' => 'Doggy',
                'pet-breed' => '-',
                'pet-weight' => 12,
                'pet-age' => 6,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '4106462020',
                'client-state' => 'Maryland',
                'client-city' => 'Baltimore',
                'client-address' => '8 Paget Trail',
                'client-zip' => '785244',
            ],
            [
                'client-first-name' => 'Norah',
                'client-last-name' => 'Gives',
                'client-email' => 'ngives9@smugmug.com',
                'pet-type' => 'dog',
                'pet-name' => 'King',
                'pet-breed' => '-',
                'pet-weight' => 45,
                'pet-age' => 9,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '8134612728',
                'client-state' => 'Florida',
                'client-city' => 'Tampa',
                'client-address' => '2184 Main Hill',
                'client-zip' => '456987',
            ],
            [
                'client-first-name' => 'Shelby',
                'client-last-name' => 'Tull',
                'client-email' => 'stulla@wufoo.com',
                'pet-type' => 'dog',
                'pet-name' => 'Shell',
                'pet-breed' => '-',
                'pet-weight' => 8,
                'pet-age' => 11,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5055801538',
                'client-state' => 'New Mexico',
                'client-city' => 'Las Cruces',
                'client-address' => '9 Truax Center',
                'client-zip' => '789632',
            ],
            [
                'client-first-name' => 'Alistair',
                'client-last-name' => 'Gumbley',
                'client-email' => 'agumbleyb@diigo.com',
                'pet-type' => 'dog',
                'pet-name' => 'Ally',
                'pet-breed' => '-',
                'pet-weight' => 23.5,
                'pet-age' => 11,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5078332385',
                'client-state' => 'Minnesota',
                'client-city' => 'Rochester',
                'client-address' => '3 Drewry Avenue',
                'client-zip' => '586974',
            ],
            [
                'client-first-name' => 'Ignatius',
                'client-last-name' => 'Thies',
                'client-email' => 'ithiesc@cbc.ca',
                'pet-type' => 'dog',
                'pet-name' => 'Igy',
                'pet-breed' => '-',
                'pet-weight' => 7,
                'pet-age' => 2,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '7815591768',
                'client-state' => 'Massachusetts',
                'client-city' => 'Cambridge',
                'client-address' => '63 Annamark Street',
                'client-zip' => '741258',
            ],
            [
                'client-first-name' => 'Ynes',
                'client-last-name' => 'Flook',
                'client-email' => 'yflooke@youtu.be',
                'pet-type' => 'dog',
                'pet-name' => 'Lady',
                'pet-breed' => '-',
                'pet-weight' => 12,
                'pet-age' => 3,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5615141135',
                'client-state' => 'Florida',
                'client-city' => 'West Palm Beach',
                'client-address' => '0789 Corry Pass',
                'client-zip' => '965413',
            ],
            [
                'client-first-name' => 'Kalvin',
                'client-last-name' => 'Chawkley',
                'client-email' => 'kchawkleyd@wikia.com',
                'pet-type' => 'cat',
                'pet-name' => 'Hera',
                'pet-breed' => '-',
                'pet-weight' => 4.5,
                'pet-age' => 3,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5175573697',
                'client-state' => 'Michigan',
                'client-city' => 'Lansing',
                'client-address' => '946 Del Mar Lane',
                'client-zip' => '789632',
            ],
            [
                'client-first-name' => 'Merridie',
                'client-last-name' => 'Drohun',
                'client-email' => 'mdrohunf@moonfruit.com',
                'pet-type' => 'cat',
                'pet-name' => 'Onix',
                'pet-breed' => '-',
                'pet-weight' => 5,
                'pet-age' => 4,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '4801226109',
                'client-state' => 'Arizona',
                'client-city' => 'Gilbert',
                'client-address' => '1 Sachtjen Hill',
                'client-zip' => '745632',
            ],
            [
                'client-first-name' => 'Pascale',
                'client-last-name' => 'Mote',
                'client-email' => 'pmoteg@hatena.ne.jp',
                'pet-type' => 'cat',
                'pet-name' => 'Sable',
                'pet-breed' => '-',
                'pet-weight' => 3.5,
                'pet-age' => 6,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '3104381278',
                'client-state' => 'California',
                'client-city' => 'Santa Monica',
                'client-address' => '177 Sunfield Point',
                'client-zip' => '852147',
            ],
            [
                'client-first-name' => 'Claudine',
                'client-last-name' => 'Andriesse',
                'client-email' => 'candriesseh@1688.com',
                'pet-type' => 'cat',
                'pet-name' => 'Dragon',
                'pet-breed' => 'Rug Doll',
                'pet-weight' => 7.5,
                'pet-age' => 9,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5409712074',
                'client-state' => 'Virginia',
                'client-city' => 'Richmond',
                'client-address' => '0135 International Trail',
                'client-zip' => '452189',
            ],
            [
                'client-first-name' => 'Idalia',
                'client-last-name' => 'Sainter',
                'client-email' => 'isainteri@over-blog.com',
                'pet-type' => 'bird',
                'pet-name' => 'Lord',
                'pet-breed' => 'Great horned owl',
                'pet-weight' => 2.5,
                'pet-age' => 4,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '9715306373',
                'client-state' => 'Oregon',
                'client-city' => 'Portland',
                'client-address' => '590 Judy Lane',
                'client-zip' => '563987',
            ],
            [
                'client-first-name' => 'Abram',
                'client-last-name' => 'De Minico',
                'client-email' => 'ademinicoj@whitehouse.gov',
                'pet-type' => 'dog',
                'pet-name' => 'Willy',
                'pet-breed' => '-',
                'pet-weight' => 10,
                'pet-age' => 3,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '6068180908',
                'client-state' => 'Kentucky',
                'client-city' => 'London',
                'client-address' => '7759 Ridge Oak Junction',
                'client-zip' => '357951',
            ],
            [
                'client-first-name' => 'Lemar',
                'client-last-name' => 'Bolzmann',
                'client-email' => 'lbolzmannk@woothemes.com',
                'pet-type' => 'dog',
                'pet-name' => 'Nemo',
                'pet-breed' => '-',
                'pet-weight' => 22,
                'pet-age' => 7,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5129871371',
                'client-state' => 'Texas',
                'client-city' => 'Austin',
                'client-address' => '54219 Thierer Crossing',
                'client-zip' => '842691',
            ],
            [
                'client-first-name' => 'Reggi',
                'client-last-name' => 'Mulvy',
                'client-email' => 'rmulvyl@amazon.com',
                'pet-type' => 'dog',
                'pet-name' => 'Sku',
                'pet-breed' => '-',
                'pet-weight' => 11,
                'pet-age' => 6,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '6173861845',
                'client-state' => 'Massachusetts',
                'client-city' => 'Newton',
                'client-address' => '50734 Prentice Parkway',
                'client-zip' => '842953',
            ],
            [
                'client-first-name' => 'Sky',
                'client-last-name' => 'Eby',
                'client-email' => 'sebym@ning.com',
                'pet-type' => 'cat',
                'pet-name' => 'Amy',
                'pet-breed' => '-',
                'pet-weight' => 5.5,
                'pet-age' => 5,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '8185499387',
                'client-state' => 'California',
                'client-city' => 'Glendale',
                'client-address' => '08 Kingsford Plaza',
                'client-zip' => '8426951',
            ],
            [
                'client-first-name' => 'Nancy',
                'client-last-name' => 'Britner',
                'client-email' => 'nbritnern@dailymail.co.uk',
                'pet-type' => 'cat',
                'pet-name' => 'Serval',
                'pet-breed' => '-',
                'pet-weight' => 7.5,
                'pet-age' => 6,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '8082113787',
                'client-state' => 'Hawaii',
                'client-city' => 'Honolulu',
                'client-address' => '3678 Killdeer Hill',
                'client-zip' => '741658',
            ],
            [
                'client-first-name' => 'Roze',
                'client-last-name' => 'Mapp',
                'client-email' => 'rmappo@nydailynews.com',
                'pet-type' => 'dog',
                'pet-name' => 'Bill',
                'pet-breed' => '-',
                'pet-weight' => 23,
                'pet-age' => 5,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '2482286684',
                'client-state' => 'Michigan',
                'client-city' => 'Detroit',
                'client-address' => '7 Mccormick Hill',
                'client-zip' => '846253',
            ],
            [
                'client-first-name' => 'Erica',
                'client-last-name' => 'Dallicoat',
                'client-email' => 'edallicoatp@ted.com',
                'pet-type' => 'cat',
                'pet-name' => 'Queen',
                'pet-breed' => '-',
                'pet-weight' => 6,
                'pet-age' => 11,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '5027281413',
                'client-state' => 'Kentucky',
                'client-city' => 'Louisville',
                'client-address' => '142 Monterey Court',
                'client-zip' => '852741',
            ],
            [
                'client-first-name' => 'Sansone',
                'client-last-name' => 'Iohananof',
                'client-email' => 'siohananofq@apple.com',
                'pet-type' => 'cat',
                'pet-name' => 'Sam',
                'pet-breed' => '-',
                'pet-weight' => 6,
                'pet-age' => 8,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '9173763375',
                'client-state' => 'New York',
                'client-city' => 'Bronx',
                'client-address' => '98 Wayridge Point',
                'client-zip' => '746385',
            ],
            [
                'client-first-name' => 'Dallas',
                'client-last-name' => 'MacTrustie',
                'client-email' => 'dmactrustier@symantec.com',
                'pet-type' => 'dog',
                'pet-name' => 'Miky',
                'pet-breed' => '-',
                'pet-weight' => 9.5,
                'pet-age' => 3,
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '9155366949',
                'client-state' => 'Texas',
                'client-city' => 'El Paso',
                'client-address' => '7877 Scoville Terrace',
                'client-zip' => '976431',
            ],
            [
                'client-first-name' => 'Ursala',
                'client-last-name' => 'Loomis',
                'client-email' => 'uloomiss@youtu.be',
                'pet-type' => 'other',
                'pet-name' => 'Jake',
                'pet-breed' => 'Iguana',
                'pet-weight' => '1.2',
                'pet-age' => '2',
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '7064987183',
                'client-state' => 'Georgia',
                'client-city' => 'Augusta',
                'client-address' => '27703 1st Street',
                'client-zip' => '12489',
            ],
            [
                'client-first-name' => 'Deanna',
                'client-last-name' => 'Doxsey',
                'client-email' => 'ddoxseyt@mit.edu',
                'pet-type' => 'dog',
                'pet-name' => 'Mik',
                'pet-breed' => '-',
                'pet-weight' => '11',
                'pet-age' => '4',
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '9077292799',
                'client-state' => 'Alaska',
                'client-city' => 'Anchorage',
                'client-address' => '0 6th Park',
                'client-zip' => '365742',
            ],
            [
                'client-first-name' => 'Marlane',
                'client-last-name' => 'Petre',
                'client-email' => 'mpetreu@gnu.org',
                'pet-type' => 'bird',
                'pet-name' => 'Polly',
                'pet-breed' => 'great ara',
                'pet-weight' => '1.5',
                'pet-age' => '23',
                'pet-description' => '-',
                'pet-microchipped' => 1,
                'pet-vaccinations' => 1,
                'pet-spayed' => 1,
                'pet-spayed-object' => 0,
                'pet-dietary-needs' => '-',
                'pet-veterinary-needs' => 'no',
                'pet-behavior' => '-',
                'pet-relevant-info' => '-',
                'police-involved' => 1,
                'client-protective-order' => 1,
                'abuser-details' => '-',
                'pet-abuser-access' => 0,
                'pet-how-long' => 25,
                'pet-protective-order-covered' => 1,
                'pet-client-paperwork' => 1,
                'pet-abuser-paperwork' => 0,
                'pet-boarding-options' => 1,
                'client-phone-number-type' => 'mobile',
                'client-phone-number' => '2127319411',
                'client-state' => 'New York',
                'client-city' => 'New York City',
                'client-address' => '68994 Vahlen Hill',
                'client-zip' => '123456',
            ],
            // [
            //     'client-first-name' => '',
            //     'client-last-name' => '',
            //     'client-email' => '',
            //     'pet-type' => '',
            //     'pet-name' => '',
            //     'pet-breed' => '-',
            //     'pet-weight' => '',
            //     'pet-age' => '',
            //     'pet-description' => '-',
            //     'pet-microchipped' => 1,
            //     'pet-vaccinations' => 1,
            //     'pet-spayed' => 1,
            //     'pet-spayed-object' => 0,
            //     'pet-dietary-needs' => '-',
            //     'pet-veterinary-needs' => 'no',
            //     'pet-behavior' => '-',
            //     'pet-relevant-info' => '-',
            //     'police-involved' => 1,
            //     'client-protective-order' => 1,
            //     'abuser-details' => '-',
            //     'pet-abuser-access' => 0,
            //     'pet-how-long' => 25,
            //     'pet-protective-order-covered' => 1,
            //     'pet-client-paperwork' => 1,
            //     'pet-abuser-paperwork' => 0,
            //     'pet-boarding-options' => 1,
            //     'client-phone-number-type' => 'mobile',
            //     'client-phone-number' => '',
            //     'client-state' => '',
            //     'client-city' => '',
            //     'client-address' => '',
            //     'client-zip' => '',
            // ],
            
        ];

        
        foreach ($organisations as $organisation) 
        {    
            // get advocate from current organisation
            $user = User::where('organisation_id', $organisation->id)->first();
            
            // create client in need
            foreach ($demoEntries as $entry) 
            {
                $petType = DB::table('object_types')
                        ->where([
                            ['type', '=', 'pet'],
                            ['value', '=', $entry['pet-type']]
                        ])
                        ->first();
                
                // new client
                $client = new Client();
                $client->organisation_id = $organisation->id;
                $client->first_name = $entry['client-first-name'];
                $client->last_name = $entry['client-last-name'];
                $client->email = $entry['client-email'];
                $client->best_way_to_reach = "email";
                $client->pets_count = 1;
                $client->slug = str_slug($entry['client-first-name'] . ' ' . $entry['client-last-name'] , '-');
                $client->save();

                // new pet
                $pet = new Pet();
                $pet->client_id = $client->id;
                $pet->organisation_id = $organisation->id;
                $pet->pet_type_id = $petType->id;
                $pet->name = $entry['pet-name'];
                $pet->breed = $entry['pet-breed'];
                $pet->weight = $entry['pet-weight'];
                $pet->age = $entry['pet-age'];
                $pet->description = $entry['pet-description'];
                $pet->microchipped = $entry['pet-microchipped'];
                $pet->vaccinations = $entry['pet-vaccinations'];
                $pet->sprayed = $entry['pet-spayed'];
                $pet->objection_to_spray = $entry['pet-spayed-object'];
                $pet->dietary_needs = $entry['pet-dietary-needs'];
                $pet->vet_needs = $entry['pet-veterinary-needs'];
                $pet->temperament = $entry['pet-behavior'];
                $pet->aditional_info = $entry['pet-relevant-info'];
                $pet->slug = str_slug($entry['pet-name'], '-');
                $pet->save();

                // new client application
                $application = new Application();
                $application->client_id = $client->id;
                $application->organisation_id = $organisation->id;
                $application->created_by_advocate_id = $user->id;
                $application->police_involved = $entry['police-involved'];
                $application->protective_order = $entry['client-protective-order'];
                $application->abuser_notes = $entry['abuser-details'];
                $application->save();

                // new pet application
                $application_pet = new ApplicationPet();
                $application_pet->application_id = $application->id;
                $application_pet->pet_id = $pet->id;
                $application_pet->client_id = $client->id;
                $application_pet->organisation_id = $organisation->id;
                $application_pet->created_by_advocate_id = $user->id;
                $application_pet->abuser_visiting_access = $entry['pet-abuser-access'];
                $application_pet->estimated_lenght_of_housing = $entry['pet-how-long'];
                $application_pet->pet_protective_order = $entry['pet-protective-order-covered'];
                $application_pet->client_legal_owner_of_pet = $entry['pet-client-paperwork'];
                $application_pet->abuser_legal_owner_of_pet = $entry['pet-abuser-paperwork'];
                $application_pet->explored_boarding_options = $entry['pet-boarding-options'];
                $application_pet->save();

                // get phone type
                $phone_type = ObjectType::where([
                    ['type', '=', 'phone'],
                    ['value', '=', $entry['client-phone-number-type']]
                ])->first();

                // save client phone number
                $phone = new Phone();
                $phone->entity_type = 'client';
                $phone->entity_id = $client->id;
                $phone->phone_type_id = $phone_type->id;
                $phone->number = $entry['client-phone-number'];
                $phone->save();

                // save client address
                $address = new Address();
                $address->entity_type = 'client';
                $address->entity_id = $client->id;
                $address->state = $entry['client-state'];
                $address->city = $entry['client-city'];
                $address->street = $entry['client-address'];
                $address->zip_code = $entry['client-zip'];
                $address->save();

            } // end foreach entry


        } // end foreach organisation


    }
}
